name: Merge to Dev

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Jalankan Tes
    - name: Run Tests
      run: |
        echo "Running tests..."
        exit 0

    # Merge ke branch dev jika tes berhasil
    - name: Merge to Dev
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git fetch --all
        git checkout dev
        git merge ${{ github.ref_name }} --no-ff --allow-unrelated-histories -m "Auto-merge from ${{ github.ref_name }}" || echo "Merge failed"
        git checkout --theirs .github/workflows/merge-to-dev.yml || echo "No conflict in workflows"
        git add .github/workflows/merge-to-dev.yml || true
        git commit -m "Resolved conflicts automatically" || echo "No changes to commit"
        git push origin dev || echo "Push failed, check branch protection rules."

    # Debugging Git
    - name: Debug Git Logs
      run: |
        git status
        git log --oneline -5
