name: Merge to Dev

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Jalankan Tes (gunakan perintah tes yang sesuai untuk proyek Anda)
    - name: Run Tests
      run: |
        # Ganti dengan perintah tes Anda
        echo "Running tests..."
        exit 0  # Return 0 jika tes berhasil

    # Merge ke branch dev jika tes berhasil
    - name: Merge to Dev
      if: success() # Merge hanya jika tes berhasil
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git fetch --all  # Tarik semua branch
        git checkout dev # Pindah ke branch dev
        git merge ${{ github.ref_name }} --no-ff -m "Auto-merge from ${{ github.ref_name }}" # Merge branch yang berubah ke dev
        git push origin dev # Push perubahan ke remote branch dev
